"""update

Revision ID: d8cb0095df29
Revises: 
Create Date: 2024-07-12 01:35:23.002809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cb0095df29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('help_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('school_student_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_student_reports', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('help_articles', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('client_reports', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
